LIBS += \
-lkernel -lutils -lfofi -lGoo -lsplash -lxpdf  \
-lkernel -lutils -lfofi -lGoo -lsplash -lxpdf  \
-lkernel -lutils -lfofi -lGoo -lsplash -lxpdf  \
-lt1

INCPATH += -I. -I./core/xpdf/ -I./core

CFLAGS += -g
CXXFLAGS += -g
